import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from '@/components/AnimatedText'


export default function Home() {
  return (
    <>
      <Head>
        <title>Aryadeep's Portfolio</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>

        <Layout className='pt-0'>
          <div className="justify-between w-full">
            {/* <div className='absolute flex items-center h-1/2 '> */}
            <div class="absolute flex">

              <div class="justify-start ml-20  ">       
                
                <AnimatedText text="Aryadeep Gogoi "/>
                {/* <AnimatedText className='!text-4xl' text="Arydeep Gogoi "/> */}
              </div>

              <div class="justify-end text-right w-1/2 flex items-center justify-center h-screen relative ">
                <p className=' w-1/2'>
                  TurningTurning Turning Turning Turning Turning TurningTurningTurning Turning Turning Turning Turning TurninvTurningTurning Turning Turning Turning Turning Turning

                </p>

              </div>
            </div>
             
            <div className='grid place-content-center ml-12'>
              <Image src={profilePic} alt="Aryadeep Gogoi" className='w-full h-auto' />
            </div>
            

          </div>

        </Layout>

      </main>

    </>
  )
}
